version: 2

jobs:
  test:
    docker:
      - image: openpolicyagent/opa
      - entrypoint: /opa
    steps:
      - run: opa version
      - run: opa test .

workflows:
  version: 2
  ci:
    jobs:
      - test
